# Configuration pour le plugin EverPartySpigot

# Paramètres de connexion Redis
redis:
  host: "localhost" # Adresse IP ou nom d'hôte du serveur Redis
  port: 6379 # Port par défaut de Redis
  password: "" # Mot de passe Redis (laisser vide s'il n'y a pas de mot de passe)

# Paramètres pour la création de partys
party:
  max_members: 10 # Nombre maximal de membres dans une party
  max_parties_per_player: 1 # Nombre maximal de partys par joueur
  disband_empty_party: true # Dissoudre automatiquement les partys vides lorsque le dernier joueur quitte